MACRO(RemoveCompileOption flg)

	STRING( REPLACE "${flg}" "" CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE}" )
	STRING( REPLACE "${flg}" "" CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG}" )

ENDMACRO( )
